### ISSUE TITLE
Still working with OpenCV 4? 

### ISSUE THREAD

**Issue by nategreco** [cedricve/raspicam#104]
Been a minute (7 years) since I used this API - Has anyone used it recently with OpenCV 4.8 and pi 4/5?

**Comment by nategreco** [comment]
Issue isn't OpenCV - It's MMAL.  They've migrated to libcamera.

**Comment by Minduck102** [comment]
> Vấn đề không phải là OpenCV - Đó là MMAL. Họ đã di chuyển sang libCamera.

Vậy làm cách nào để giải quyết vấn đề này.
