### ISSUE TITLE
Unable to re-capture image with new parameters

### ISSUE THREAD

**Issue by theSundayProgrammer** [cedricve/raspicam#14]
My code is something like this:

    { 
       //...
       {
         Raspicam camera;
         camera.setwidth(320);
         camera.setheight(240)
         camera.open()
         //.. get buffer size and allocate memmory
         camera.grab_retreive(buffer,length)
       }

       {
         Raspicam camera;
         camera.setwidth(320);
         camera.setheight(240)
         camera.open()
         //.. get buffer size and allocate memmory
         camera.grab_retreive(buffer,length)
       }
    }

The error on the second open is:
mmal_vc_component_enable: falied to enable component : ENOSPC

Is this a limitation of the camera and its drivers or with Raspicam?

**Comment by birgersp** [comment]
I'm guessing you should close/release the camera before re-opening it. Is there a particular reason why you are opening the camera twice?

**Comment by theSundayProgrammer** [comment]
The aim is to change the width and height or demand. Close / release has no effect on size unless I restart the application. Is there any other to change height/width?

**Comment by cedricve** [comment]
How I solved is to create it dynamically with new. 

https://github.com/kerberos-io/machinery/blob/master/include/kerberos/capture/RaspiCamera.h#L34

and delete it.

**Comment by birgersp** [comment]
What I mean is each time you want to set the width/height you can try to

- Close the camera
- Set the width/height you desire
- Open the camera

I'm not sure this will help. Regardless, you shouldn't have to create another camera each time...

**Comment by birgersp** [comment]
Also, maybe related to #16

**Comment by ihhub** [comment]
Camera ROI should not be changed when you open/make an access to camera. What happen when a camera is grabbing an image and you decide to change ROI? It's unpredictable situation. All software what I saw doesn't support such feature (change width and height after opening). I don't think this is an issue.

**Comment by theSundayProgrammer** [comment]
If you see the code, I am closing the camera, setting the dimensions and then re-opening.

**Comment by birgersp** [comment]
@theSundayProgrammer: Sorry, my bad. I didn't realize the objects were deconstructed when exiting the closed braces.
