### ISSUE TITLE
the image is bluish

### ISSUE THREAD

**Issue by dmcyang163** [cedricve/raspicam#18]
Camera.set( CV_CAP_PROP_FORMAT, CV_8UC3 );
//Camera.set( CV_CAP_PROP_WHITE_BALANCE_RED_V, -1 ); // auto whitebalance
//Camera.set( CV_CAP_PROP_WHITE_BALANCE_BLUE_U, -1 );

how to make it show better

**Comment by cedricve** [comment]
do you have an example image?

**Comment by dmcyang163** [comment]
i found that need
cvtColor(img, img, CV_BGR2RGB);

after
Camera.grab();
Camera.retrieve ( img);

but cvtColor cost 10ms

**Comment by cedricve** [comment]
see this https://github.com/cedricve/raspicam/pull/17

**Comment by cedricve** [comment]
I've merged the pull request, can you verify it now works as expected?

**Comment by dmcyang163** [comment]
thanks a lot！O(∩_∩)O

**Comment by dmcyang163** [comment]
it‘s  ok now

**Comment by mikeymclellan** [comment]
Hey guys, buy the looks of this it's now made my cameras go blue again. 

See this discussion here: https://github.com/cedricve/raspicam/pull/13

By the sounds of what 6by9 is saying it depends on camera firmware version. He's provided a fix which checks the version and adjusts appropriately.

I might apply his patch to my fork and test it and submit another pull-request to you @cedricve.

**Comment by cedricve** [comment]
@mikeymclellan nice find, indeed I remember him saying, and this was definitely the issue in this ticket. Not so cleaver to accept the pull request though. If you can send a pull request for this, with the merge of @6by9 that would be awesome!
