### ISSUE TITLE
Cmake error

### ISSUE THREAD

**Issue by AntonOsachy** [cedricve/raspicam#4]
Hello, 
I installed api to my raspberry pi and pre-build examples work fine. But when I try to build my own project (as suggested in tutorial) cmake gives an error (CMake Error at CMakeLists.txt:3 (find package) and I can't build a project :/  The location of project /raspicam and location of api /Downloads/raspicam-0.1.3
Could you help me please with this issue!?

**Comment by MohammadAftal** [comment]
try adding the flowing line:
set (CMAKE_MODULE_PATH "/usr/local/lib/cmake/${CMAKE_MODULE_PATH}")
before:
find_package(raspicam REQUIRED)
in your CMakeLists.txt

**Comment by cedricve** [comment]
Hello Mohammad

Please send a pull request.

**Comment by MohammadAftal** [comment]
Ok Cedricve, I did.

**Comment by TamaHobbit** [comment]
This was a problem for me in the very first example, included in the readme. Hence pullrequest [#32](https://github.com/cedricve/raspicam/pull/32).
