### ISSUE TITLE
Maximum fps is 33.33 for 640x480 image

### ISSUE THREAD

**Issue by ozgen92** [cedricve/raspicam#5]
With the following set up, although raspicam is capable of working at 90fps, I am unable to get 90 fps when I use grab, in a for loop. Is there a way around this?

```
Camera.set (CV_CAP_PROP_FRAME_WIDTH, 640);
Camera.set (CV_CAP_PROP_FRAME_HEIGHT, 480);
Camera.set (CV_CAP_PROP_FPS, 90);
```

**Comment by joyousrabbit** [comment]
Same question.
